---
- name: Install Redis
  apt:
    name: redis-server
    state: present
  register: redis_install


- name: Find Redis configuration file
  shell: find / -name "redis.conf" 2>/dev/null
  register: redis_conf_path
  changed_when: false
  failed_when: false
  ignore_errors: yes

- name: Display Redis config path
  debug:
    var: redis_conf_path.stdout_lines

- name: Ensure Redis config directory exists
  file:
    path: /etc/redis
    state: directory
    mode: '0755'
  when: redis_conf_path.stdout_lines | length == 0



- name: Create basic Redis config if missing
  copy:
    content: |
      # Redis configuration file
      
      # Network
      bind {{ redis_bind_ip }}
      port {{ redis_port }}
      
      # Memory management
      maxmemory {{ redis_maxmemory }}
      maxmemory-policy {{ redis_maxmemory_policy }}
      
      # Persistence
      save 900 1
      save 300 10
      save 60 10000
      appendonly yes
      
      # Other recommended settings
      protected-mode yes
      tcp-keepalive 300
      dir /var/lib/redis
      supervised systemd
    dest: /etc/redis/redis.conf
  when: redis_conf_path.stdout_lines | length == 0
  notify: restart redis

- name: Configure Redis for persistence (if config exists)
  lineinfile:
    path: "{{ redis_conf_path.stdout_lines[0] }}"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^bind', line: 'bind {{ redis_bind_ip }}' }
    - { regexp: '^port', line: 'port {{ redis_port }}' }
    - { regexp: '^maxmemory', line: 'maxmemory {{ redis_maxmemory }}' }
    - { regexp: '^maxmemory-policy', line: 'maxmemory-policy {{ redis_maxmemory_policy }}' }
    - { regexp: '^save 900 1', line: 'save 900 1' }
    - { regexp: '^save 300 10', line: 'save 300 10' }
    - { regexp: '^save 60 10000', line: 'save 60 10000' }
    - { regexp: '^appendonly', line: 'appendonly yes' }
  when: redis_conf_path.stdout_lines | length > 0
  notify: restart redis