# main.yml - Main playbook that orchestrates the entire setup
- name: Configure Genz.ad Server
  hosts: genz_servers
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - base-setup
    - postgres
    - redis
    - nginx
    - app-backend
    - app-frontend