all:
  children:
    genz_servers:
      hosts:
        server1:
          ansible_host: "52.50.19.100"
          ansible_user: "ubuntu"
          ansible_ssh_private_key_file: "/tmp/ansible_key.pem"
