- name: Install essential packages
  apt:
    name:
      - build-essential
      - git
      - ufw
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-pip
      - python3-venv
      - nginx
      - python3-certbot-nginx
      - nodejs
      - npm
    state: present

- name: Install pnpm
  shell: npm install -g pnpm
  args:
    creates: /usr/local/bin/pnpm

- name: Install PM2
  shell: npm install -g pm2
  args:
    creates: /usr/local/bin/pm2

- name: Create private key file
  copy:
    content: "{{ ssh_private_key }}"
    dest: "/tmp/ansible_key.pem"
    mode: '0600'
  delegate_to: localhost
  become: false
  state: present

- name: Ensure key has correct permissions
  file:
    path: "/tmp/ansible_key.pem"
    mode: '0600'
  delegate_to: localhost
  become: false

- name: Set hostname
  hostname:
    name: "{{ server_hostname }}"

- name: Configure UFW firewall
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - OpenSSH
    - 'Nginx Full'

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

