- name: Configure systemd service for backend
  template:
    src: backend_service.j2
    dest: /etc/systemd/system/{{ item.service_name }}.service
    mode: '0644'
  loop: "{{ backend_services }}"
  notify: Reload backend services
